### PR TITLE
Relax http dependency

### PR DESCRIPTION
**Pull request by julianrubisch**
I needed this to work with another gem in my depdency tree.

Tests look okay for me, please let me know if I can do anything!

### CODE REVIEW

**Review by etagwerker — APPROVED** [review]
@julianrubisch I'm all for relaxing this dependency, but this will generate a warning when building the gem: 

```
WARNING:  open-ended dependency on http (>= 3.3) is not recommended
  if http is semantically versioned, use:
    add_runtime_dependency 'http', '~> 3.3'
```

I don't think it is a big deal. Thoughts, @mscottford or @bronzdoc?

**Comment by julianrubisch** [comment]
Hmm is there another way to allow http 4?

**Comment by mscottford** [comment]
How about `add_runtime_dependency 'http', '>= 3.3', '< 5.0'?

**Review by etagwerker — APPROVED** [review]
@julianrubisch Great, thanks! ❤️

**Comment by etagwerker** [comment]
@julianrubisch Just released this fix in v0.5.1: https://rubygems.org/gems/harvesting/versions/0.5.1 -- Thanks! 💯

**Pull request merged**
