### PR TITLE
fix incompatibility with ruby 3

### PR DESCRIPTION
**Pull request by jhendley25**
This hasn't been heavily tested at all, but ran into this and figured I'd open a PR. Simply passing the block fixes the errors I was seeing.

### CODE REVIEW

**Review by etagwerker — COMMENTED** [review]
@jhendley25 Thanks for submitting this change! Could you please add a bit more info about the issue you are seeing? I'm curious about the failure in Ruby 3.0.0.

**Comment by jhendley25** [comment]
Actually it looks like the Ruby 3 upgrade had nothing to do with the bug. I don't know exactly why it was breaking for me but passing the test suite, but that last commit explicitly accepts and forwards the block to the recursive `each`, which fixes everything for me. Let me know if I can help here or if I should just close the PR.

**Comment by timirwin** [comment]
I'm seeing a failure on Ruby 3 due to `FrozenError (can't modify frozen String: "")` in the http 3.3.0 dependency. Looks like other forks are fixing it by updating the http gem to version 4.

**Comment by timirwin** [comment]
@jhendley25 Did you have a different work around? I have the same issue but it works with your change. My sample code iterates over users where I have more than 100 users.
```ruby
client = Harvesting::Client.new
client.users.each do; end
```

Before your branch, I get `ArgumentError: tried to create Proc object without a block` but no error after.

**Comment by jhendley25** [comment]
@timirwin I'm just using my branch until this PR gets merged or another fix is in place.

**Comment by etagwerker** [comment]
@jhendley25 Could you review the failure in CI? It seems relevant to the change you are submitting.

**Comment by jhendley25** [comment]
@etagwerker Looks like CI is passing now. The previous issue was because my initial fix broke pagination. It's working properly now.

**Review by etagwerker — APPROVED** [review]
@jhendley25 Great, thanks! 💯

**Comment by etagwerker** [comment]
@jhendley25 @timirwin Just released this fix in v0.5.1: https://rubygems.org/gems/harvesting/versions/0.5.1 -- Thanks! 💯

**Pull request merged**
