### PR TITLE
Fix error when delete entity request goes wrong

### LINKED ISSUE #60: TimeEntry: Delete with a 404 code will raise `NoMethodError`
https://github.com/fastruby/harvesting/blob/e98c0dca8331911e8176c4179b0d65c893db8508/lib/harvesting/client.rb#L118

Will raise `*** NoMethodError Exception: undefined method `UnprocessableRequest'`

fix: 

```ruby
raise UnprocessableRequest.new(response.to_s) unless response.code.to_i == 200 
```

Thanks for the gem, it's great quality.
I'll try to make a PR to add some behaviours, but I didn't find the time to add the tests yet.

### PR DESCRIPTION
**Pull request by martinjaimem**
Closes #60

### CODE REVIEW

**Review by bronzdoc — APPROVED** [review]
Nice catch @martinjaimem, thank you!

**Comment by bronzdoc** [comment]
@martinjaimem can you add a test for this?

**Comment by etagwerker** [comment]
@martinjaimem @bronzdoc I went ahead and added a test over here: https://github.com/fastruby/harvesting/commit/b211ff39f00acf6513bc7de7d3a4fd14f8fe6f23#diff-e9c4f6f93bc0a6899ca789ad7f1002c294d9850ccc2cd8c8cd9f4831c364d145R115

**Comment by etagwerker** [comment]
@martinjaimem @bronzdoc Just released this fix in v0.5.1: https://rubygems.org/gems/harvesting/versions/0.5.1 -- Thanks! 💯

**Pull request merged**
